### ISSUE TITLE
Cannot build android with cca using the com.google.cordova.admob plugin and chrome.identity

### ISSUE THREAD

**Issue by Knorcedger** [MobileChromeApps/cordova-plugin-chrome-apps-identity#3]
Im opening this issue here as well, since I got no answer by the admob plugin developer yet. [Issue link](https://github.com/floatinghotpot/cordova-admob-pro/issues/128)

Im a using google cca to build a cordova app, but after adding the chrome.identity Plugin and Cordova admob pro, I cant build the app anymore. The terminal error says: *UNEXPECTED TOP-LEVEL EXCEPTION: com.android.dex.DexException: Multiple dex files define Lcom/google/andr
oid/gms/actions/ReserveIntents;* (Full error log below)

**System Details**  
Windows
cca v0.7.0
If you need anything else please let me know.

**Replication Steps**
1. Install cca
2. In a terminal: `cca create app`
3. `cd app`
4. `cca platform add android`
5. Open app/www/manifest.json and in the permissions array add: identity e.g. `"permissions": ["<all_urls>", "identity"]`
6. `cca build android` Builds fine.
7. `cca plugin add com.google.cordova.admob`
8. `cca build android` Fails

**Full error log from terminal**

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexArmv7Debug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        C:\Users\TsoumiAc\AppData\Local\Android\android-sdk\build-tools\22.0.1\d
x.bat --dex --no-optimize --output C:\Users\TsoumiAc\Desktop\app\platforms\andro
id\build\intermediates\dex\armv7\debug --input-list=C:\Users\TsoumiAc\Desktop\ap
p\platforms\android\build\intermediates\tmp\dex\armv7\debug\inputList.txt
Error Code:
        2
Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Lcom/google/andr
oid/gms/actions/ReserveIntents;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.ja
va:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:
554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:
535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)

                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main
.java:454)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
                at com.android.dx.command.dexer.Main.run(Main.java:246)
                at com.android.dx.command.dexer.Main.main(Main.java:215)
                at com.android.dx.command.Main.main(Main.java:106)



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 24.141 secs

C:\Users\TsoumiAc\Desktop\app\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\Users\TsoumiAc\Desktop\app\pl
atforms\android\gradlew cdvBuildDebug -b C:\Users\TsoumiAc\Desktop\app\platforms
\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: C:\Users\TsoumiAc\Desktop\app\platfo
rms\android\cordova\build.bat: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: C:\Users\TsoumiAc\Desktop\app\platforms\android\cordova\build.bat: Comman
d failed with exit code 1
    at ChildProcess.whenDone (C:\Users\TsoumiAc\AppData\Roaming\npm\node_modules
\cca\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:131
:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
```

**Comment by gbenvenuti** [comment]
Hi @Knorcedger,

I've seen this a number of times, assuming you're using cordova 5 then you should fork the admob plugin and replace this line in `plugin.xml`:

```xml
<dependency id="com.google.playservices" url="https://github.com/floatinghotpot/google-play-services" commit="r19" />
```
with something like this

```xml
<framework src="com.google.android.gms:play-services-ads:+" />
```

Then install the admob plugin from your local drive or pushed fork.

Please note I haven't tested the above but this is how I've solved a number of dex issues with other plugins .

Good luck!

**Comment by floatinghotpot** [comment]
I tried the suggest framework, but unfortunately it builds error...

```
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-ads:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/
     Required by:
         :android:unspecified
```

**Comment by agrieve** [comment]
Sounds like you don't have the "Google Repository" installed. You can add it via the Android SDK Manager. (type `android` into a terminal)

**Comment by floatinghotpot** [comment]
Yes, you are correct. 

After installing following extras in Android SDK Manager, the build is successful.

* Android Support Repository
* Android Support Library
* Google Play services
* Google Repository

Thanks!

**Comment by Knorcedger** [comment]
Thank you guys for the help :)
